# deployment.yaml
apiVersion: compute/v1
kind: Instance
metadata:
  name: bulkhead-vm
spec:
  machineType: zones/us-central1-a/machineTypes/e2-standard-4  # 4 CPU, 16 GB RAM
  disks:
  - boot: true
    autoDelete: true
    initializeParams:
      sourceImage: projects/debian-cloud/global/images/family/debian-11
      diskSizeGb: 20
  networkInterfaces:
  - network: global/networks/default
    accessConfigs:
    - type: ONE_TO_ONE_NAT
      name: External NAT
  metadata:
    items:
    - key: startup-script
      value: |
        #!/bin/bash
        apt-get update
        apt-get install -y python3 python3-pip git
        
        # Clone repository
        cd /opt
        git clone https://github.com/danteboe/ExpMantenibilidad2.git
        cd ExpMantenibilidad2
        
        # Install dependencies
        pip3 install -r requirements.txt
        
        # Set environment variables
        export SERVER_TYPE=bulkhead
        export DJANGO_SECRET_KEY="your-secret-key-here"
        export DEBUG=False
        
        # Get internal IPs of database instances (you'll need to update these)
        export WRITE_DB_IP="10.128.0.3:8000"  # Update with actual write DB internal IP
        export READ_DB_IP="10.128.0.4:8000"   # Update with actual read DB internal IP
        
        # Run migrations and populate database
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 populate_db.py
        
        # Start the application
        python3 manage.py runserver 0.0.0.0:8000
  tags:
    items:
    - bulkhead-server
  serviceAccounts:
  - email: default
    scopes:
    - https://www.googleapis.com/auth/cloud-platform

---
apiVersion: compute/v1
kind: Instance
metadata:
  name: escribir-vm
spec:
  machineType: zones/us-central1-a/machineTypes/e2-standard-4  # 4 CPU, 16 GB RAM
  disks:
  - boot: true
    autoDelete: true
    initializeParams:
      sourceImage: projects/debian-cloud/global/images/family/debian-11
      diskSizeGb: 20
  networkInterfaces:
  - network: global/networks/default
    accessConfigs:
    - type: ONE_TO_ONE_NAT
      name: External NAT
  metadata:
    items:
    - key: startup-script
      value: |
        #!/bin/bash
        apt-get update
        apt-get install -y python3 python3-pip git
        
        # Clone repository
        cd /opt
        git clone https://github.com/danteboe/ExpMantenibilidad2.git
        cd ExpMantenibilidad2
        
        # Install dependencies
        pip3 install -r requirements.txt
        
        # Set environment variables
        export SERVER_TYPE=write
        export DJANGO_SECRET_KEY="your-secret-key-here"
        export DEBUG=False
        
        # Run migrations and populate database
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 populate_db.py
        
        # Start the application
        python3 manage.py runserver 0.0.0.0:8000
  tags:
    items:
    - write-db-server
  serviceAccounts:
  - email: default
    scopes:
    - https://www.googleapis.com/auth/cloud-platform

---
apiVersion: compute/v1
kind: Instance
metadata:
  name: lectura-vm
spec:
  machineType: zones/us-central1-a/machineTypes/e2-standard-4  # 4 CPU, 16 GB RAM
  disks:
  - boot: true
    autoDelete: true
    initializeParams:
      sourceImage: projects/debian-cloud/global/images/family/debian-11
      diskSizeGb: 20
  networkInterfaces:
  - network: global/networks/default
    accessConfigs:
    - type: ONE_TO_ONE_NAT
      name: External NAT
  metadata:
    items:
    - key: startup-script
      value: |
        #!/bin/bash
        apt-get update
        apt-get install -y python3 python3-pip git
        
        # Clone repository
        cd /opt
        git clone https://github.com/danteboe/ExpMantenibilidad2.git
        cd ExpMantenibilidad2
        
        # Install dependencies
        pip3 install -r requirements.txt
        
        # Set environment variables
        export SERVER_TYPE=read
        export DJANGO_SECRET_KEY="your-secret-key-here"
        export DEBUG=False
        
        # Run migrations and populate database
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 populate_db.py
        
        # Start the application
        python3 manage.py runserver 0.0.0.0:8000
  tags:
    items:
    - read-db-server
  serviceAccounts:
  - email: default
    scopes:
    - https://www.googleapis.com/auth/cloud-platform

---
apiVersion: compute/v1
kind: Firewall
metadata:
  name: allow-django-app
spec:
  allowed:
  - IPProtocol: TCP
    ports:
    - "8000"
  direction: INGRESS
  sourceRanges:
  - 0.0.0.0/0
  targetTags:
  - bulkhead-server
  - write-db-server
  - read-db-server